### ISSUE TITLE
regression: v1.8.0 causes ApiErrors while instantiating a client instance

### ISSUE THREAD

**Issue by ckuethe** [lacework/python-sdk#100]
Simply instantiating the client causes an API error for me.
```python
lwc = LaceworkClient(account=api_creds['account'], api_key=api_creds['keyId'], api_secret=api_creds['secret'])
```

That line works and allows me to query my lacework account using `laceworksdk==1.7.0`. After upgrading to the latest release (1.8.0 as of this writing) I get a server error:

```python
ApiError                                  Traceback (most recent call last)
/tmp/ipykernel_43438/2254193892.py in <module>
----> 1 lwc = LaceworkClient(account=api_creds['account'],api_key=api_creds['keyId'], api_secret=api_creds['secret'])
      2 
      3 now = datetime.datetime.utcnow()
      4 then = now - datetime.timedelta(days=7)

~/.local/lib/python3.10/site-packages/laceworksdk/api/__init__.py in __init__(self, account, subaccount, api_key, api_secret, instance, base_domain, profile)
    133 
    134         # Create an HttpSession instance
--> 135         self._session = HttpSession(
    136             self._account,
    137             self._subaccount,

~/.local/lib/python3.10/site-packages/laceworksdk/http_session.py in __init__(self, account, subaccount, api_key, api_secret, base_domain)
     61 
     62         # Get an access token
---> 63         self._check_access_token()
     64 
     65     def _retry_session(self,

~/.local/lib/python3.10/site-packages/laceworksdk/http_session.py in _check_access_token(self)
    100         if self._access_token is None or self._access_token_expiry < datetime.now(timezone.utc):
    101 
--> 102             response = self._get_access_token()
    103 
    104             # Parse and restructure the returned date (necessary for Python 3.6)

~/.local/lib/python3.10/site-packages/laceworksdk/http_session.py in _get_access_token(self)
    169 
    170             # Validate the response
--> 171             self._check_response_code(response, DEFAULT_SUCCESS_RESPONSE_CODES)
    172 
    173             self._print_debug_response(response)

~/.local/lib/python3.10/site-packages/laceworksdk/http_session.py in _check_response_code(self, response, expected_response_codes)
    118             raise RateLimitError(response)
    119         else:
--> 120             raise ApiError(response)
    121 
    122     def _print_debug_response(self, response):

ApiError: [500] Internal Server Error - Internal Error
```

**Comment by alannix-lw** [comment]
Hey @ckuethe!  We made the following change in `1.8.0` of the python-sdk: https://github.com/lacework/python-sdk/pull/98/files

There was an issue previously where if a user had provided their account as a parameter or an environment variable, the `subaccount` would still get loaded via the default profile in their `~/.lacework.toml` file.  The intent of this change was to prevent that from happening.

Can you check your `~/.lacework.toml` file (if you have one) to see if the subaccount was being erroneously loaded prior to `1.8.0`?

**Comment by ckuethe** [comment]
I have no subaccount in my `.lacework.toml`. Just a `[default]` section with an `account` element.

**Comment by alannix-lw** [comment]
Thanks for checking on that @ckuethe - after a little more digging, it looks like another change (https://github.com/lacework/python-sdk/pull/97/files) may have caused this.  We tried to move the domain validation logic upstream, but there are cases where the base_domain will be `None`

Can you confirm that you are providing the account as an FQDN with `.lacework.net` as the suffix?  If so, you should be able to remove the `.lacework.net` domain as a temporary workaround.

I'll get a fix for the issue released shortly.

**Comment by ckuethe** [comment]
Yes, I'm using an FQDN for the account name. My secrets file (and in memory representation of my account credentials) looks like this:

```
{
    "keyID": "EXAMPLE_biglonghexstring",
    "secret": "believeitornotanotherhexstring",
    "account": "example.lacework.net"
}
```

Removing `.lacework.net` from the account works with v1.8.0, eg.
```python
with open("lw_creds.json") as ifd:
    api_creds = json.load(ifd)

lwc = LaceworkClient(
        account=api_creds['account'].replace('.lacework.net', ''),
        api_key=api_creds['keyId'],
        api_secret=api_creds['secret']
    )

print(len(lwc.user_profile.get()['data'][0]['url']) > 0)

```
