### ISSUE TITLE
Hi is there a way to pass proxy parameter to the sdk? 

### ISSUE THREAD

**Issue by jaya2991** [lacework/python-sdk#102]

**Comment by alannix-lw** [comment]
Hi @jaya2991!  Sorry for the slow reply on this - although you can't currently explicitly set a proxy while instantiating an instance of `LaceworkClient` - the SDK leverages the requests library, and therefore will honor the `HTTPS_PROXY` environment variable.  Please let me know if this is acceptable for your use case!

**Comment by jaya2991** [comment]
thanks for your response, this helps @alannix-lw
