### ISSUE TITLE
.agent_info.search() not including `Content-Type: application/json` header: 400 errors

### ISSUE THREAD

**Issue by zachsis** [lacework/python-sdk#115]
using the `.agent_info.search(json=...)` call results in a 400 error. Reviewing output from the debug logs indicates that it is missing the `Content-Type: application/json` header which is likely the reason for the errors. 

```
def collectagents(self):
    postpayload = { 'timeFilter': {}}
    postpayload['timeFilter']['startTime'] = datetime.datetime.strftime(datetime.datetime.now() + datetime.timedelta(days=-1), "%Y-%m-%dT00:00:00Z")
    postpayload['timeFilter']['endTime'] = datetime.datetime.strftime(datetime.datetime.now(), "%Y-%m-%dT%H:%M:%SZ")
    agents = self.lw.agent_info.search(json=json.dumps(postpayload))
    for i in agents:
        print(i)
    print(agents)
```

Debug output: 

```
Wed, 01 Mar 2023 09:32:21 - laceworksdk.http_session - INFO - POST request to URI: https://instructure.lacework.net/api/v2/AgentInfo/search
Wed, 01 Mar 2023 09:32:21 - laceworksdk.http_session - DEBUG - Request headers: 
{
  "User-Agent": "laceworksdk-python-client/1.9.0",
  "Accept-Encoding": "gzip, deflate",
  "Accept": "*/*",
  "Connection": "keep-alive",
  "Authorization": "Bearer REDACTED",
  "Org-Access": "false"
}
Wed, 01 Mar 2023 09:32:21 - laceworksdk.http_session - DEBUG - POST request data:
Data: None
JSON: {"timeFilter": {"startTime": "2023-02-28T00:00:00Z", "endTime": "2023-03-01T09:32:17Z"}}
Wed, 01 Mar 2023 09:32:21 - urllib3.connectionpool - DEBUG - https://instructure.lacework.net:443 "POST /api/v2/AgentInfo/search HTTP/1.1" 400 51
```

**Comment by zachsis** [comment]
That makes sense, thanks @ipcrm ! That does resolve the issue. I was a bit confused with the named argument being set to `json=` that it was expecting json, not a `dict` or `string`. One more question I have though, Once this generator returns the dictionary object, how can i use the `lw.agent_info.search()` method to query the `i['paging']['urls']['nextPage']` when the `i['paging']['totalRows'] are > 5000 ?

**Comment by ipcrm** [comment]
Agreed; the argument being named `json` is not particularly clear!

Apologies in advance if I'm not fully understanding the question around the generator, but as I understand it you should simply be able to use the following:

```
agents = lacework_client.agent_info.search(json=postpayload)

for a in agents:
    print(a) # example
```

And the generator will handle all the paging on your behalf (https://github.com/lacework/python-sdk/blob/main/laceworksdk/api/search_endpoint.py#L43-L53)


Does that answer your question or am I way off the mark?

**Comment by ipcrm** [comment]
@zachsis I hope that answered your question! Feel free to re-open or start a new issue if not!
