### ISSUE TITLE
feat: User Groups

### ISSUE THREAD

**Issue by JPLachance** [lacework/python-sdk#119]
# Feature Request

**Describe the Feature Request**
Implement the new User Groups API: https://youraccount.lacework.net/api/v2/docs#tag/UserGroups

**Is your feature request related to a problem? Please describe**
I need to automate users provisioning in Lacework.

**Describe Preferred Solution**
Then end goal is to drive user groups using this Python SDK.

**Comment by tmac1973** [comment]
User Groups have been implemented
