### ISSUE TITLE
Error: Initializing a LaceworkClient object

### ISSUE THREAD

**Issue by jdomeracki** [lacework/python-sdk#72]
Hi, we've stumbled upon an issue when initializing a LaceworkClient object.
The client does not seem to work properly when the obligatory parameter _account_ == _subdomain.lacework.net_

## To Reproduce
SDK v1.3.0
Python 3.7+

Intialize the client object with values derived from the downloadable .json key file:
```
lw = LaceworkClient(account=os.getenv("LW_ACCOUNT"), # subdomain.lacework.net
                    api_key=os.getenv("LW_API_KEY"),
                    api_secret=os.getenv("LW_API_SECRET"))
```
When run this should result in the following (shortened) error:
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**In contrast when the _account_ == _subdomain_ then client works as expected.**

## Expected behaviour
In my opinion the _account_ parameter parsing should be adjusted so that _subdomain.lacework.net_ and _subdomain_ would be handled gracefully.
Alternatively the documentation should state clearly that only the user-specific subdomain should be provided.

**Comment by alannix-lw** [comment]
Thank you for reporting this @jdomeracki !  I honestly thought we had addressed this issue previously, but looks like it had slipped through the cracks.  I just created a small PR (#73 ) to have this issue resolved.  We'll cut a new release soon which contains the fix.
