### ISSUE TITLE
SDK Documentation?

### ISSUE THREAD

**Issue by relsqui** [lacework/python-sdk#81]
Hi! Thanks for maintaining this; it's been really helpful for making my API scripting more readable/maintainable. I had some trouble getting started, though. Here are places where I got stuck and more information in the README (or in other SDK-specific docs) would have helped:

* What methods are available on the client? Linking to the full API docs would be a good start, but I'd also need to know how to translate endpoints to method names. (Seems to be pascal -> snake case, but doesn't say that anywhere.)
* When do I need to use a submethod like `.get()` or `.search()`? What methods like exist? How do I format the arguments? Which ones are required? (I was surprised that `queries.execute()` requires time bound arguments -- when I run queries through the Lacework CLI I don't need to supply that, and the API docs don't mention it. If it weren't for the test files I'd still be stumped.)
* The how-to says I need to auth with arguments to the client, the environment variables section says I can use variables, and a comment in the example implies I can use my Lacework config file, but I wish all of that was summarized in one explanation of my auth options. (The [terraform provider](https://registry.terraform.io/providers/lacework/lacework/latest/docs) does a great job of this.)
* What does this SDK do when a method call fails? What errors should I catch, and how do I get response codes and messages out of them?
* How are responses formatted? When should I expect them to be paged and how do I unpage them?

I don't need immediate answers to any of these -- a combination of reading the source code and just trying stuff to see what breaks eventually got me there. But I'd love to see these things documented so the next person doesn't have to.

**Comment by M1Gd0nPG** [comment]
Adding to the list above, I can't find which filters are accepted/allowed for the various searches.  Example: can I filter by the repo field when doing a containers.vulnerability.search()?  (the answer is kind of but it's not as simple as "repo"..).  I find myself spending way too much time trying to figure out what I can and can not do with this SDK, I'm going back to the CLI.

**Comment by jon-stewart** [comment]
Hi @relsqui and @M1Gd0nPG, thanks for providing the feedback.  This is now tracked internally and will be prioritised.

My apologies that this is only being looked at now.

**Comment by tmac1973** [comment]
Hi all. Thanks so much for your feedback! We've recently completed a documentation revamp of the python-sdk which hopefully will address the issues raised here. The new documentation is available here:

https://lacework.github.io/python-sdk/

Some highlights include: 

- A rewrite of all docstrings which are used to generate the documentation above. These indicate the required types for all parameters as well as return types. 
- Class documentation contains convenient links to the API documentation, allowing you to easily understand what endpoint is called by what class. This should also allow you to understand what filters are available per endpoint as the available fields are listed in the API documentation. 
- A section on authentication in the documentation
- Updated examples both on the documentation site as well as in the repo. All tested to work. 
- Clear documentation on which search methods return generators vs. dicts (containing lists)

I hope this helps to make the SDK more easy to use. There is an accompanying 3.0.0 release as many other issues have been addressed as well. Please do continue to let us know how we can improve this SDK.
